# Files generated by data_processing.sh
DATA_DIR=$1
rm -r $1
rm -r pre_trained_models
rm -r data_processing/nltk_data
rm -r model_novelty/data
rm model_multi_sentence/*.json
rm -r post_processing_and_ensemble/model_ensemble/data
rm post_processing_and_ensemble/*.dat
rm -r model_single_sentence/pmbert_smooth_5epoch_5fcv/new_train_splits
rm model_single_sentence/pmbert_smooth_5epoch_5fcv/new_annotated_test_pd.json
rm model_single_sentence/pmbert_smooth_5epoch_5fcv/new_annotated_train_pd.json
rm model_single_sentence/pmbert_smooth_5epoch_5fcv/no_rel.csv
rm -r model_single_sentence/pmbert_smooth_5epoch_alldata/new_train_splits
rm model_single_sentence/pmbert_smooth_5epoch_alldata/new_annotated_test_pd.json
rm model_single_sentence/pmbert_smooth_5epoch_alldata/new_annotated_train_pd.json
rm model_single_sentence/pmbert_smooth_5epoch_alldata/no_rel.csv

# Files generated by run_model_single_sentence_5fcv.sh
rm -r model_single_sentence/pmbert_smooth_5epoch_5fcv/fine_tuned_models
rm model_single_sentence/pmbert_smooth_5epoch_5fcv/selected_checkpoints.json
rm -r model_single_sentence/pmbert_smooth_5epoch_5fcv/pred_configs
rm -r model_single_sentence/pmbert_smooth_5epoch_5fcv/predictions

# Files generated by run_model_single_sentence_alldata.sh
rm -r model_single_sentence/pmbert_smooth_5epoch_alldata/fine_tuned_models
rm model_single_sentence/pmbert_smooth_5epoch_alldata/selected_checkpoints.json
rm -r model_single_sentence/pmbert_smooth_5epoch_alldata/pred_configs
rm -r model_single_sentence/pmbert_smooth_5epoch_alldata/predictions

# Files generated by run_model_multi_sentence.sh
rm -r model_multi_sentence/roberta_BS16_lr3e-5_RS*
rm model_multi_sentence/log.roberta_BS16_lr3e-5_RS*
rm model_multi_sentence/err.roberta_BS16_lr3e-5_RS*
rm model_multi_sentence/majority_voting_RE_14models_stronger.csv

# Files generated by run_model_novelty.sh
rm -r model_novelty/roberta_Novel_punct*
rm model_novelty/log.roberta_Novel_punct*
rm model_novelty/err.roberta_Novel_punct*
rm model_novelty/majority_voting_7models_HMT.csv

# Files generated by post_processing_and_ensemble.sh
rm post_processing_and_ensemble/model_ensemble/test.csv
rm post_processing_and_ensemble/model_ensemble/multi_sentence_output.csv
rm post_processing_and_ensemble/model_ensemble/novelty_output.csv
rm post_processing_and_ensemble/model_ensemble/test_ensemble_mv.tsv
rm -r post_processing_and_ensemble/16*
rm -r post_processing_and_ensemble/32*

# Remove the final submission file
rm post_processing_and_ensemble/model_ensemble/submission.csv

# Virtual environments
rm -r data_processing/.venv
rm -r post_processing_and_ensemble/.venv
rm -r model_single_sentence/.venv
rm -r model_novelty/.venv
rm -r model_multi_sentence/.venv
